loop_on_end = true
pause_at_start = false

[defaults]
format = "{percent}\n#{time}\n"
autostart = true

[[sessions]]
id = "work"
name = "Work"
duration = "25m"
command = "notify-send 'Work Done!' 'Time to take a small break' -u critical -t 20000"

[[sessions]]
id = "rest"
name = "Rest"
duration = "5m"
command = "notify-send 'Rest Done!' 'Time to get back to work' -u critical -t 20000"
