# Window rules for hyprland

 windowrule {
     name = supress-maximize
     match:class = .* 
     
     suppress_event = maximize 
 }

# Make firefox PIP player work.
windowrule {
    name = fix-firefox-pip
    match:class = firefox
    match:title = Picture-in-Picture

    float = on
    size = 30% 30%
    move = 69% 69%
}
